// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class PapelessFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-YnFpJu6tgZWGd3ss6gDLW7xINEgsLE',
    appId: '1:165551757169:web:b794d0c840d6212b7048d0',
    messagingSenderId: '165551757169',
    projectId: 'core-paperless',
    authDomain: 'core-paperless.firebaseapp.com',
    databaseURL: 'https://core-paperless.firebaseio.com',
    storageBucket: 'core-paperless.appspot.com',
    measurementId: 'G-L20HKFFG5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-YnFpJu6tgZWGd3ss6gDLW7xINEgsLE',
    appId: '1:165551757169:android:7e68f16f9b469dcb7048d0',
    messagingSenderId: '165551757169',
    projectId: 'core-paperless',
    storageBucket: 'core-paperless.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-YnFpJu6tgZWGd3ss6gDLW7xINEgsLE',
    appId: '1:178058752050:ios:91bafec44f09361bc54c2b', // falta
    messagingSenderId: '165551757169',
    projectId: 'core-paperless',
    databaseURL: 'https://core-paperless.firebaseio.com',
    storageBucket: 'core-paperless.appspot.com',
    iosClientId:
        '178058752050-ckjbdh1efacfqrjffa45s4q8ahelke8i.apps.googleusercontent.com', // fala
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-YnFpJu6tgZWGd3ss6gDLW7xINEgsLE',
    appId: '1:178058752050:ios:91bafec44f09361bc54c2b', // falta
    messagingSenderId: '165551757169',
    projectId: 'core-paperless',
    databaseURL: 'https://core-paperless.firebaseio.com',
    storageBucket: 'core-paperless.appspot.com',
    iosClientId:
        '178058752050-ckjbdh1efacfqrjffa45s4q8ahelke8i.apps.googleusercontent.com', // fala
    iosBundleId: 'com.example.testApp',
  );
}
