// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_eJA7isoNVWQ-KKBRAD8LmFDFp5r9H0',
    appId: '1:178058752050:web:7d2d605192741936c54c2b',
    messagingSenderId: '178058752050',
    projectId: 'testpwa-4631f',
    authDomain: 'testpwa-4631f.firebaseapp.com',
    databaseURL: 'https://testpwa-4631f-default-rtdb.firebaseio.com',
    storageBucket: 'testpwa-4631f.appspot.com',
    measurementId: 'G-C4WPZWJZYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yKcq9wJUMeL4Nh3n2NcciKQjcwg0Cqw',
    appId: '1:178058752050:android:cc4e9cde0afedcf9c54c2b',
    messagingSenderId: '178058752050',
    projectId: 'testpwa-4631f',
    databaseURL: 'https://testpwa-4631f-default-rtdb.firebaseio.com',
    storageBucket: 'testpwa-4631f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uoPzjOzbttav01l9Z7hsBMScARnzJ34',
    appId: '1:178058752050:ios:91bafec44f09361bc54c2b',
    messagingSenderId: '178058752050',
    projectId: 'testpwa-4631f',
    databaseURL: 'https://testpwa-4631f-default-rtdb.firebaseio.com',
    storageBucket: 'testpwa-4631f.appspot.com',
    iosClientId: '178058752050-ckjbdh1efacfqrjffa45s4q8ahelke8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uoPzjOzbttav01l9Z7hsBMScARnzJ34',
    appId: '1:178058752050:ios:91bafec44f09361bc54c2b',
    messagingSenderId: '178058752050',
    projectId: 'testpwa-4631f',
    databaseURL: 'https://testpwa-4631f-default-rtdb.firebaseio.com',
    storageBucket: 'testpwa-4631f.appspot.com',
    iosClientId: '178058752050-ckjbdh1efacfqrjffa45s4q8ahelke8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
